kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

services:
  - name: nats-streaming
    image: nats-streaming
    command: [-mc, 0]
    ports:
      - 4222

steps:
  - name: tests
    image: golang:latest
    environment:
      CODECOV_TOKEN:
        from_secret: CODECOV_TOKEN
      COVERALLS_TOKEN:
        from_secret: COVERALLS_TOKEN
    commands:
      - export STAN_HOST="nats-streaming"
      - export NATS_HOST="nats-streaming"
      - go build
      - go run github.com/onsi/ginkgo/ginkgo -r --randomizeAllSpecs --failFast --cover --trace
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get update
      - apt-get install -y nodejs
      - go test github.com/moleculer-go/compatibility/moleculerjs
      - go run github.com/modocache/gover ./ coverage.txt
      - curl -s https://codecov.io/bash | bash || echo "Error uploading codecov"
      - go run github.com/mattn/goveralls -coverprofile=coverage.txt -service=drone.io || echo "Error uploading coveralls"
